# Generated by Django 4.0.4 on 2022-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobile_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('mobile_name', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('network', models.CharField(max_length=120)),
            ],
        ),
    ]
